Login feature added
danielstanojkov-quantox/php_admin pull request #1
Opened 2021-05-07 08:15 UTC by danielstanojkov-quantox

2021-05-07 10:39 UTC, davorminchorov requested changes
There are a few small issues that need to be fixed and can be improved.

Please follow the PSR rules for code styling.

Also, add type hints and return types for all methods and properties as well as docblock comments.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/Hash.php
> +        $hmac = hash_hmac($hash_algo, $ciphertext_raw, $encryption_key, true);
Please use camelCase names for the variables.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/Redirect.php
> +    public static function To($uri)
Method names should start with lowercase letters.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/Storage.php
> +        if (!File::exists(USERS)) File::createStorageFolder();
You can use class constants for things like USERS.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/Storage.php
> +class Storage
This class name is too generic, rename it to something more specific like User or move the code related to users specifically to a different class.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/Storage.php
> +        return $user[0];
#This will throw an error if it's an empty array. Also rename $user to $users.

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/functions.php
> +    if (count($data) == 0) return;
Always use triple equals. ===

2021-05-07 10:39 UTC, davorminchorov commented on app/Helpers/functions.php
> +    return $str;
$str -> $string avoid using abbreviations and/or generic names.

2021-05-07 10:39 UTC, davorminchorov commented on app/Http/Controllers/Dashboard.php
> +    $data = [];
You can set the method to have $data parameter as empty array instead of assigning it to a variable and passing it to the view method.

2021-05-07 10:39 UTC, davorminchorov commented on app/Http/Controllers/Login.php
> +        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
You can create a class Server and have a method that will check for the different method types to simplify this logic.

2021-05-07 10:39 UTC, davorminchorov commented on config/config.php
> +define('APPROOT', dirname(dirname(__FILE__)));
You can move these into a class and use them as class constants instead for better readability.

2021-05-10 06:38 UTC, internalle commented on app/Helpers/File.php
> +    public static function makeFile($directory, $filename, $content): void
You probably don't need directory and filename separatedly when creating a file. So just $filename and the path will be included with the filename

2021-05-10 07:28 UTC, internalle commented on app/Helpers/File.php
> +    public static function createStorageFolder(): void
Its considered a good practice to have the same naming for all methods. So if most of them are prepended with makeFolder or makeFile, this should probably be makeStorageDirectory.

Other thing is that I think its better to have this storage directory and file creation within other class, but not this helper class. This class can be used for File/Folder manipulation so suggest to put the app storage directory creation and file creaton on other place

2021-05-10 07:28 UTC, internalle commented on app/Helpers/Hash.php
> +        if (function_exists('mb_strlen')) {
You don't have to check if mb_strlen exist, it should always exist. So I think its better to only use that one

2021-05-10 07:28 UTC, internalle commented on app/Helpers/Server.php
> +class Server
You might add RequestClass and have isPost and isGet methods in there

2021-05-10 07:28 UTC, internalle commented on app/Http/Controllers/Dashboard.php
> +    if (!IsAuthenticatedMiddleware::handle()) Redirect::to('/login');
My personal opinion is that we shoudn't get used to these shortcuts. Its more readable if you have the whole thing like:

if (!IsAuthenticatedMiddleware::handle())  {
  Redirect::to('/login');
}

2021-05-10 07:28 UTC, internalle commented on app/Http/Controllers/Login.php
> +        Database::connect($host, $username, $password);
Please use singleton objects to work with connection, not static classes

2021-05-10 07:28 UTC, internalle commented on app/Http/Controllers/Login.php
> +        $host = $_POST['host'];
You might have getRequest() method in Server, which will return you request object. Then use the request object to check the requestType or to get post or get data with the help of classes

2021-05-10 07:28 UTC, internalle commented on app/Libraries/Database.php
> +      Session::flash('login_failed', self::$error);
Setting flash messages or redirection logic shouldn't be part of the database class. So probably do it in the controller or make a new class that will handle this

2021-05-11 07:23 UTC, davorminchorov requested changes
A few more tweaks can be done.

2021-05-11 07:23 UTC, davorminchorov commented on .vscode/launch.json
> +    "version": "0.2.0",
You can add this file to .gitignore.

2021-05-11 07:23 UTC, davorminchorov commented on app/Helpers/Hash.php
> +    private static function hash_equals_custom($knownString, $userString): bool
Please use camelCase for method names and add parameter type hints ecerywhere.

2021-05-11 07:23 UTC, davorminchorov commented on app/Helpers/UserStorage.php
> +            return $user->id != $id;
Always use !== or === to avoid type related bugs.

2021-05-11 07:23 UTC, davorminchorov commented on app/Libraries/Controller.php
> +  public function model($model): object
See if you can use dependency injection / the Reflection API to replace the usage of this method completely.

2021-05-11 10:36 UTC, davorminchorov commented on app/Models/User.php
> +class User extends Controller
Do you need to extend the controller? A model shouldn't extend the controller, but it can extend other models.

2021-05-11 10:37 UTC, davorminchorov commented on config/config.php
> +define('APPROOT', dirname(dirname(__FILE__)));
You can create a class named App or something similar which can contain all of these constants as class constants.

2021-05-11 10:39 UTC, davorminchorov commented on config/config.php
> +define('APPROOT', dirname(dirname(__FILE__)));
You can also add helper methods to use some of these in your views as well.

2021-05-12 07:30 UTC, davorminchorov approved these changes
Looks good.

2021-05-12 07:58 UTC, internalle approved these changes

2021-05-12 08:01 UTC, merged