Listing databases
danielstanojkov-quantox/php_admin pull request #2
Opened 2021-05-17 08:28 UTC by danielstanojkov-quantox

2021-05-17 09:41 UTC, davorminchorov requested changes
There are a few things that you need to change, most of them are minor things.

2021-05-17 09:41 UTC, davorminchorov commented on app/Helpers/UserStorage.php
> +            return (int)$user->id === (int) $id;
This might not work properly,  you might need to do `((int)$user->id) === ((int) $id)`

2021-05-17 09:41 UTC, davorminchorov commented on app/Http/Controllers/Api.php
> +            die(json_encode(array('message' => $th->getMessage(), 'code' => 1337)));
The code should be 500

2021-05-17 09:41 UTC, davorminchorov commented on app/Http/Controllers/Dashboard.php
> +      session('db_err', $th->getMessage());
It's a good practice to avoid using abbreviations and use the full words, so in this case `db_error` would be more appropriate

2021-05-17 09:41 UTC, davorminchorov commented on app/Http/Controllers/Dashboard.php
> +      session('db_err', $th->getMessage());
Same as above.

2021-05-17 09:41 UTC, davorminchorov commented on app/Libraries/Database.php
> +      $stmt = self::$pdo->query("SHOW TABLES FROM $databaseName;");
Same as above: $stmt -> $statement
Also, you are missing bindings here. `:databaseName` instead of `$databaseName` for security reasons.

2021-05-17 09:41 UTC, davorminchorov commented on app/Libraries/Database.php
> +      $stmt = self::$pdo->query("SELECT * FROM $tableName;");
Same as above: $stmt -> $statement
Also, you are missing bindings here. `:databaseName` instead of `$databaseName` for security reasons.

2021-05-17 09:41 UTC, davorminchorov commented on app/Libraries/Database.php
> +  // public function query($sql): void
If you don't need the commented code, you can always delete it and come back based on the file history to retrieve it if you need it.

2021-05-18 11:29 UTC, davorminchorov approved these changes
Looks good.

2021-05-20 13:01 UTC, internalle approved these changes

2021-05-20 13:11 UTC, merged